### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by kevinpapst** [infeeeee/kimai-cmd#1]
I'd like to seeSSSL support, as you can expect that many or most of the applications nowadays run with HTTPS encryption (thanks to Letsencrypt and browsers warning if you submit password with http connection).

What do you need exactly to be able to test it? The demo runs under https:
https://demo.kimai.org
You could use the "admin/changeme" account for testing.

**Comment by infeeeee** [comment]
I totally forgot about the demo site. I will test it there, thanks!

**Comment by infeeeee** [comment]
I added SSL support, download from [releases ](https://github.com/infeeeee/kimai-cmd/releases)
